### ISSUE TITLE
Feature Request: #to_h

### ISSUE THREAD

**Issue by MadBomber** [gshutler/useragent#2]
It would be interesting if you could generate a hash with symbolized keys and string values.  This would fit in well with the functionality of the addressable and cgi gems.  Using those two and your useragent gem we could parse out everything of interest in the URL and UserAgent strings.

**Comment by gshutler** [comment]
Released in 0.13.2

**Comment by MadBomber** [comment]
Installed the new release into my load_db program.  Found a problem with an Opera string...

```ruby
1426896049.802419  DEBUG: Source: ./load_db.rb:78:in `process_transaction'
1426896049.802419  DEBUG: a_hash[:ua] -=> "Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.15231/26.1411; U; en) Presto/2.8.119 Version/10.54"
1426896049.802419  DEBUG: ua_object -=> [#<UserAgent:0x000000057e3d58
  @comment=["J2ME/MIDP", "Opera Mini/4.1.15231/26.1411", "U", "en"],
  @product="Opera",
  @version=#<UserAgent::Version 9.80>>,
 #<UserAgent:0x000000057e3880
  @comment=nil,
  @product="Presto",
  @version=#<UserAgent::Version 2.8.119>>,
 #<UserAgent:0x000000057e3470
  @comment=nil,
  @product="Version",
  @version=#<UserAgent::Version 10.54>>]

Done.

/home/Dewayne/.rvm/gems/ruby-2.2.0/gems/useragent-0.13.2/lib/user_agent/browsers/base.rb:102:in `to_h': undefined method `to_a' for "4.1.15231":String (NoMethodError)
```
Dewayne
  o-*

**Comment by MadBomber** [comment]
wrote a test program got these results..  Opera is bad!  Long Live Rock and Roll...

```text
1426948130.708818  DEBUG: Source: ./test_useragent.rb:88:in `<main>'
1426948130.708818  DEBUG: total_cnt -=> 20411
1426948130.708818  DEBUG: good_cnt -=> 20405
1426948130.708818  DEBUG: parse_err -=> 0
1426948130.708818  DEBUG: to_h_err -=> 6

Opera/9.80 (Android; Opera Mini/6.5.27049/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "6.5.27049":String

Opera/9.80 (Android; Opera Mini/6.5.27452/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "6.5.27452":String

Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.13572/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "4.1.13572":String

Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.15231/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "4.1.15231":String

Opera/9.80 (J2ME/MIDP; Opera Mini/4.2.14038/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "4.2.14038":String

Opera/9.80 (J2ME/MIDP; Opera Mini/6.5.26955/26.1411; U; en) Presto/2.8.119 Version/10.54
undefined method `to_a' for "6.5.26955":String
```

Recap: out of 20,411 unique user agent strings there were zero exceptions from the parse method and only 6 exceptions from the to_h method.  Those 6 were the same exception type.  It was an Opera string every time.

Dewayne
  o-*

**Comment by gshutler** [comment]
Thanks, I'll look into it.

**Comment by gshutler** [comment]
Found that the Opera user agent was returning a string directly rather than wrapping it in a `Version`. That's fixed and released in 0.13.3.

Thanks for the report.

**Comment by MadBomber** [comment]
Thanks for the new feature.  I've successfully loaded a large number of browser transactions into a rethinkDB table using the new to_h feature.

**Comment by gshutler** [comment]
:+1:
